# Generated by Django 2.2.5 on 2022-07-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220705_0927'),
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='three_pcl_img_patch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcl_patch', models.FileField(max_length=128, upload_to='3D_patch/', verbose_name='点云')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
